# For more information about the available options please visit: http://go/catalog-info (VPN required)
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    github.com/project-slug: Unity-Technologies/U6-First-Person-Multiplayer
  name: U6-First-Person-Multiplayer
  description: "Advocacy First Person Co-op Multiplayer Sample"
  labels:
    costcenter: "3050"
  tags:
    - planned-public
    - enterprise
spec:
  type: other
  lifecycle: production
  owner: Unity-Technologies/advocacy
